version: 2

build:
  os: ubuntu-20.04
  tools:
    python: "3.9"
  commands:
    - git submodule init
    - git submodule update
    - pip install -U poetry
    - poetry install
    - . .venv/bin/activate && cd docs && make html
    - mkdir _readthedocs
    - cp -r docs/_build/html/ _readthedocs/

submodules:
  include: all
