[tool.poetry]
name = "etl"
version = "0.1.0"
description = ""
authors = ["Lars Yencken <lars@yencken.org>"]

[tool.poetry.scripts]
etl = 'etl.command:main'
reindex = 'etl.reindex:reindex'
publish = 'etl.publish:publish'

[tool.poetry.dependencies]
python = "^3.9"
owid-catalog = {path = "vendor/owid-catalog-py", develop = true}
walden = {path = "vendor/walden", develop = true}
click = "^8.0.1"
PyYAML = "^5.4.1"
papermill = "^2.3.3"
jupyterlab = "^3.1.13"
mysqlclient = "^2.0.3"
SPARQLWrapper = "^1.8.5"
openpyxl = "^3.0.9"
sh = "^1.14.2"
boto3 = "^1.18.54"
awscli = "^1.20.54"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
black = {extras = ["jupyter"], version = "^21.9b0"}
mypy = "^0.910"
flake8 = "^3.9.2"
watchdog = "^2.1.5"
PyYAML = "^5.4.1"
argh = "^0.26.2"
jupyter = "^1.0.0"
ipython = "^7.27.0"
matplotlib = "^3.4.3"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
