[tool.poetry]
name = "etl"
version = "0.1.0"
description = ""
authors = ["Lars Yencken <lars@yencken.org>"]

[tool.poetry.dependencies]
python = "^3.9"
pandas = "^1.3.3"
jsonschema = "^3.2.0"
pandas-stubs = "^1.2.0"
dataclasses-json = "^0.5.6"
pyarrow = "^5.0.0"
ipdb = "^0.13.9"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
black = "^21.9b0"
mypy = "^0.910"
flake8 = "^3.9.2"
watchdog = "^2.1.5"
PyYAML = "^5.4.1"
argh = "^0.26.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
